version: '1.5.0'

components:
  - name: DocumentStore
    type: OpenSearchDocumentStore
    params:
      host: "localhost"
      username: "admin"
      password: "admin"
      port: 9200
      scheme: "http"
      index: "document-benchmark-sparse-1"
      similarity: "cosine"
  - name: Reader
    type: FARMReader
    params:
      model_name_or_path: "deepset/roberta-base-squad2"
  - name: Retriever
    type: BM25Retriever
    params:
      document_store: DocumentStore
      top_k: 5
  - name: TextFileConverter
    type: TextConverter
  - name: Preprocessor
    type: PreProcessor
    params:
      split_by: passage
      split_length: 1
      split_respect_sentence_boundary: False

pipelines:
  - name: query
    nodes:
      - name: Retriever
        inputs: [Query]
      - name: Reader
        inputs: [Retriever]

  - name: indexing
    nodes:
      - name: TextFileConverter
        inputs: [File]
      - name: Preprocessor
        inputs: [TextFileConverter]
      - name: Retriever
        inputs: [Preprocessor]
      - name: DocumentStore
        inputs: [Retriever]
